CoreLibraryProj/Controllers/AuthorsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CoreLibraryProj;
using Microsoft.AspNetCore.Authorization;

namespace CoreLibraryProj.Controllers
{
    [Authorize(Roles = "admin,editor")]
    public class AuthorsController : Controller
    {
        private readonly CoreLibraryContext _context;

        public AuthorsController(CoreLibraryContext context)
        {
            _context = context;
        }

        // GET: Authors
        public async Task<IActionResult> Index()
        {
            if (User.Identity.IsAuthenticated == false) { return Redirect("~/Home"); }
            else return View(await _context.Authors.ToListAsync());
        }

        // GET: Authors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _context.Authors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }

        // GET: Authors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Authors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,AuthorName,AuthorBirthDate")] Author author)
        {
            if (ModelState.IsValid)
            {
                _context.Add(author);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }

        // GET: Authors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _context.Authors.FindAsync(id);
            if (author == null)
            {
                return NotFound();
            }
            return View(author);
        }

        // POST: Authors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,AuthorName,AuthorBirthDate")] Author author)
        {
            if (id != author.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(author);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AuthorExists(author.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }

        // GET: Authors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _context.Authors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }

        // POST: Authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var author = await _context.Authors.FindAsync(id);
            _context.Authors.Remove(author);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AuthorExists(int id)
        {
            return _context.Authors.Any(e => e.Id == id);
        }
    }
}

CoreLibraryProj/Controllers/RolesController.cs
using CoreLibraryProj.ViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace CoreLibraryProj.Controllers
{
    [Authorize(Roles ="admin")]
    public class RolesController : Controller
    {

        RoleManager<IdentityRole> _roleManager;
        UserManager<User> _userManager;
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            if (User.Identity.IsAuthenticated == false) { return Redirect("~/Home"); }
            return View(_roleManager.Roles.ToList());
        }
        public IActionResult UserList() => View(_userManager.Users.ToList());

        public async Task<IActionResult> Edit(string userId)
        {
            // отримуємо користувача
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                //список ролей користувача
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            // отримуємо користувача
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // список ролей користувача
                var userRoles = await _userManager.GetRolesAsync(user);
                // получаем все роли
                var allRoles = _roleManager.Roles.ToList();
                // список ролей, які було додано
                var addedRoles = roles.Except(userRoles);
                // список ролей, які було видалено
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }

    }
}

CoreLibraryProj/Controllers/StatsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CoreLibraryProj.Controllers
{
    public class StatsController : Controller
    {
        // GET: StatsController
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated == false) { return Redirect("~/Home"); }
            return View();
        }

    }
}

CoreLibraryProj/Controllers/UsersController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using CoreLibraryProj.Models;
using CoreLibraryProj.ViewModel;
using Microsoft.AspNetCore.Authorization;
namespace CoreLibraryProj.Controllers
{   
    [Authorize(Roles ="admin")]
    public class UsersController : Controller
    {
        UserManager<User> _userManager;

        public UsersController(UserManager<User> userManager)
        {
            _userManager = userManager;
        }

        public IActionResult Index() => View(_userManager.Users.ToList());

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(CreateUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = new User { Email = model.Email, UserName = model.Email, Year = model.Year };
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(model);
        }

        public async Task<IActionResult> Edit(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            EditUserViewModel model = new EditUserViewModel { Id = user.Id, Email = user.Email, Year = user.Year };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    user.Email = model.Email;
                    user.UserName = model.Email;
                    user.Year = model.Year;

                    var result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
            }
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                IdentityResult result = await _userManager.DeleteAsync(user);
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> ChangePassword(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            ChangePasswordViewModel model = new ChangePasswordViewModel { Id = user.Id, Email = user.Email };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    var _passwordValidator =
                        HttpContext.RequestServices.GetService(typeof(IPasswordValidator<User>)) as IPasswordValidator<User>;
                    var _passwordHasher =
                        HttpContext.RequestServices.GetService(typeof(IPasswordHasher<User>)) as IPasswordHasher<User>;

                    IdentityResult result =
                        await _passwordValidator.ValidateAsync(_userManager, user, model.NewPassword);
                    if (result.Succeeded)
                    {
                        user.PasswordHash = _passwordHasher.HashPassword(user, model.NewPassword);
                        await _userManager.UpdateAsync(user);
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Пользователь не найден");
                }
            }
            return View(model);
        }
    }
}

CoreLibraryProj/Views/Shared/HeaderItems.cshtml
<head>
    <link rel="stylesheet" type="text/css" href="/css/BookList.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
     <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Roboto+Slab:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
      <link rel="stylesheet" href="/css/Sidebar.css"/>
</head>
<body style="width:100%; height:100%;"> 
   


<div style="width:100%; height:65px; margin:0 auto;"> 
<a href="@Url.Action("Index","Books")" style="" ><img class="logo_group" src="/lib/layout-img/logo_group.png" /> </a>
<a asp-controller="Books" asp-action="Logout" class="logout_group" style="margin-right:5%;"> 
<p id="logout_text" style="position:relative; top:8px">Вийти</p>
<img class="logout_img" src="/lib/layout-img/logout.png" />
 </a>
 </div>



 <script src="/js/sidebar.js"></script>
 </body>

CoreLibraryProj/Views/Shared/Sidebar.cshtml
<header>
   <link rel="stylesheet" href="/css/Sidebar.css"/>
</header>

<body>
    <nav id="sidebar" class="sidebar_visible">
        <span style="border-bottom:1px solid black; height:50px; display:flex; flex-direction:row; justify-content:space-around;">Мої сторінки <span class="cross_span" onclick="toggle_sidebar()">+</span> </span>
        @{
            Dictionary<string, string> displayornot = new Dictionary<string, string>()
            {
                ["Books_Index"] = "display:block",
                ["Rubrics_Index"]="display:block",
                ["Roles_Index"]="display:block",
                ["Roles_UserList"]="display:block",
                ["Stats_Index"]="display:block",
                ["Authors_Index"]="display:block",
                ["Languages_Index"]="display:block",
                ["Users_Index"]="display:block"

            };


            if (User.IsInRole("user") && !User.IsInRole("admin") && !User.IsInRole("editor"))
            {
                displayornot["Roles_Index"] = "display:none";
                displayornot["Rubrics_Index"] = "display:none";
                displayornot["Roles_UserList"] = "display:none";
                displayornot["Authors_Index"] = "display:none";
                displayornot["Languages_Index"] = "display:none";
                displayornot["Users_Index"] = "display:none";


            }
            else if (User.IsInRole("editor") && !User.IsInRole("admin"))
            {
                displayornot["Roles_Index"] = "display:none";
                displayornot["Roles_UserList"] = "display:none";
                displayornot["Users_Index"] = "display:none";
            }

            else if (!User.IsInRole("user") && !User.IsInRole("editor") && !User.IsInRole("admin"))
            {
                displayornot["Roles_Index"] = "display:none";
                displayornot["Rubrics_Index"] = "display:none";
                displayornot["Roles_UserList"] = "display:none";
                displayornot["Authors_Index"] = "display:none";
                displayornot["Languages_Index"] = "display:none";
                displayornot["Users_Index"] = "display:none"; 
            }

        }
        
        <a asp-controller="Books" asp-action="Index" class="sidebar_item">Книги</a>
        <a asp-controller="Rubrics" asp-action="Index" style="@displayornot["Rubrics_Index"]" class="sidebar_item">Рубрики</a>
        <a asp-controller="Roles" asp-action="Index" style="@displayornot["Roles_Index"]" class="sidebar_item">Ролі</a>
        <a asp-controller="Authors" asp-action="Index" style="@displayornot["Authors_Index"]" class="sidebar_item">Автори</a>
        <a asp-controller="Languages" asp-action="Index" style="@displayornot["Languages_Index"]" class="sidebar_item">Мови</a>
        <a asp-controller="Users" asp-action="Index" style="@displayornot["Users_Index"]" class="sidebar_item">Керування користувачами</a>
        <a asp-controller="Roles" asp-action="UserList" style="@displayornot["Roles_UserList"]" class="sidebar_item">Керування правами доступу</a>
        <a asp-controller="Stats" asp-action="Index" class="sidebar_item">Статистика</a>

      
</nav>
<div class="toggle_sidebar" onclick="toggle_sidebar()"></div>

<script src="/js/sidebar.js"></script>
</body>

CoreLibraryProj/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoreLibraryProj</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CoreLibraryProj.styles.css" asp-append-version="true" />
</head>
<body>
    <header >
       
        <nav style="display:none" class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CoreLibraryProj</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">

        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div  class="container">
            &copy; 2022 - CoreLibraryProj - Development
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>