CoreLibraryProj/Models/Rubric.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CoreLibraryProj
{
    public partial class Rubric
    {
        public Rubric()
        {
            Books = new HashSet<Book>();
        }

        public int Id { get; set; }
        [Display(Name = "Назва рубрики")]
        public string? RubricName { get; set; }

        public virtual ICollection<Book> Books { get; set; }
    }
}

CoreLibraryProj/Controllers/RubricsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CoreLibraryProj;
using Microsoft.AspNetCore.Authorization;
using ClosedXML.Excel;

namespace CoreLibraryProj.Controllers
{
    [Authorize(Roles ="admin,editor")]
    public class RubricsController : Controller
    {
        private readonly CoreLibraryContext _context;

        public RubricsController(CoreLibraryContext context)
        {
            _context = context;
        }

        // GET: Rubrics
        public async Task<IActionResult> Index()
        {
            if (User.Identity.IsAuthenticated == false) { return Redirect("~/Home"); }
            return View(await _context.Rubrics.ToListAsync());
        }

        // GET: Rubrics/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rubric = await _context.Rubrics
                .FirstOrDefaultAsync(m => m.Id == id);
            if (rubric == null)
            {
                return NotFound();
            }

            return View(rubric);
        }

        // GET: Rubrics/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Rubrics/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,RubricName")] Rubric rubric)
        {
            if (ModelState.IsValid)
            {
                _context.Add(rubric);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(rubric);
        }

        // GET: Rubrics/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rubric = await _context.Rubrics.FindAsync(id);
            if (rubric == null)
            {
                return NotFound();
            }
            return View(rubric);
        }

        // POST: Rubrics/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,RubricName")] Rubric rubric)
        {
            if (id != rubric.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(rubric);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RubricExists(rubric.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(rubric);
        }

        // GET: Rubrics/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rubric = await _context.Rubrics
                .FirstOrDefaultAsync(m => m.Id == id);
            if (rubric == null)
            {
                return NotFound();
            }

            return View(rubric);
        }

        // POST: Rubrics/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var rubric = await _context.Rubrics.FindAsync(id);
            _context.Rubrics.Remove(rubric);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RubricExists(int id)
        {
            return _context.Rubrics.Any(e => e.Id == id);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Import(IFormFile fileExcel)
        {
            if (ModelState.IsValid)
            {
                if (fileExcel != null)
                {
                    using (var stream = new FileStream(fileExcel.FileName, FileMode.Create))
                    {
                        await fileExcel.CopyToAsync(stream);
                        using (XLWorkbook workBook = new XLWorkbook(stream, XLEventTracking.Disabled))
                        {
                            //перегляд усіх листів (в даному випадку категорій)
                            foreach (IXLWorksheet worksheet in workBook.Worksheets)
                            {
                                //worksheet.Name - назва категорії. Пробуємо знайти в БД, якщо відсутня, то створюємо нову
                                Rubric newcat;
                                var c = (from cat in _context.Rubrics
                                         where cat.RubricName.Contains(worksheet.Name)
                                         select cat).ToList();
                                if (c.Count > 0)
                                {
                                    newcat = c[0];
                                }
                                else
                                {
                                    newcat = new Rubric();
                                    newcat.RubricName = worksheet.Name;

                                    //додати в контекст
                                    _context.Rubrics.Add(newcat);
                                }
                                //перегляд усіх рядків                    
                                foreach (IXLRow row in worksheet.RowsUsed().Skip(1))
                                {
                                    try
                                    {

                                        Book book = new Book();
                                        book.BookName = row.Cell(1).Value.ToString();
                                        book.BookDescription = row.Cell(2).Value.ToString();
                                        book.BookRubric = newcat;
                                        string book_author_name = row.Cell(3).Value.ToString();

                                        int checker = 0;
                                        foreach (Book books in _context.Books.ToList())
                                        {
                                            if (books.BookName == book.BookName) checker++;
                                        }
                                        if (checker==0) _context.Books.Add(book);

                                        checker = 0;
                                        int auth_id = 0;
                                        foreach (Author auth in _context.Authors.ToList())
                                        {
                                            if (auth.AuthorName == book_author_name) { checker++; auth_id = auth.Id; }
                                        }
                                        if (checker != 0) book.BookAuthorId = auth_id;
                                        else
                                        {
                                            Author auth_to_add = new Author();
                                            auth_to_add.AuthorName = book_author_name;
                                            _context.Authors.Add(auth_to_add);
                                            _context.SaveChanges();

                                            checker = 0;
                                            foreach (Author auth_in in _context.Authors.ToList())
                                            {
                                                if (auth_in.AuthorName == book_author_name) auth_id = auth_in.Id;
                                            }
                                            book.BookAuthorId=auth_id;
                                        }

                                        
                                    }
                                    catch (Exception e)
                                    {
                                        

                                    }
                                }
                            }
                        }
                    }
                }

                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Export()
        {
            CoreLibraryContext db = new CoreLibraryContext();
            using (XLWorkbook workbook = new XLWorkbook(XLEventTracking.Disabled))
            {
                var categories = _context.Rubrics.Include("Books").ToList();
                //тут, для прикладу ми пишемо усі книжки з БД, в своїх проєктах ТАК НЕ РОБИТИ (писати лише вибрані)
                foreach (var c in categories)
                { 
                    var worksheet = workbook.Worksheets.Add(c.RubricName);

                    worksheet.Cell("A1").Value = "Назва";
                    worksheet.Cell("B1").Value = "Короткий опис";                  
                    worksheet.Cell("C1").Value = "Автор";                  
                    worksheet.Cell("D1").Value = "Файл з повним текстом твору";                  

CoreLibraryProj/Views/Rubrics/Create.cshtml
@model CoreLibraryProj.Rubric

@{
    ViewData["Title"] = "Створення рубрики";
}

@await Html.PartialAsync("Sidebar")
@await Html.PartialAsync("HeaderItems")
<h1 style="">Створити</h1>
<h4>Рубрику</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RubricName" class="control-label"></label>
                <input asp-for="RubricName" class="form-control" />
                <span asp-validation-for="RubricName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Створити" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Повернутися до переліку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CoreLibraryProj/Views/Rubrics/Delete.cshtml
@model CoreLibraryProj.Rubric

@{
    ViewData["Title"] = "Видалення";
}
@await Html.PartialAsync("Sidebar")
@await Html.PartialAsync("HeaderItems")


<h1 style="">Видалення</h1>
<h3>Ви впевнені, що бажаєте видалити цю рубрику?</h3>
<div>
    
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RubricName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RubricName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Видалити" class="btn btn-danger" /> |
        <a asp-action="Index">Повернутися до переліку рубрик</a>
    </form>
</div>

CoreLibraryProj/Views/Rubrics/Details.cshtml
@model CoreLibraryProj.Rubric

@{
    ViewData["Title"] = "Деталі";
}

<h1>Рубрика</h1>

<div>
    <h4>Rubric</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RubricName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RubricName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CoreLibraryProj/Views/Rubrics/Edit.cshtml
@model CoreLibraryProj.Rubric

@{
    ViewData["Title"] = "Редагування рубрики";
}
@await Html.PartialAsync("Sidebar")
@await Html.PartialAsync("HeaderItems")

<h1 style="">Редагувати</h1>
<h4>Рубрику:</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="RubricName" class="control-label"></label>
                <input asp-for="RubricName" class="form-control" />
                <span asp-validation-for="RubricName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Зберегти" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Повернутися до переліку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CoreLibraryProj/Views/Rubrics/Index.cshtml
@model IEnumerable<CoreLibraryProj.Rubric>

@{
    ViewData["Title"] = "Перелік рубрик";
}

<style>
   
</style>

@await Html.PartialAsync("Sidebar")
@await Html.PartialAsync("HeaderItems")

<h1 style="">Рубрики</h1>

<p>
    <a asp-action="Create">Додати нову</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RubricName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RubricName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Редагувати</a> |
                
                <a asp-action="Delete" asp-route-id="@item.Id">Видалити</a>
            </td>
        </tr>
}
    </tbody>
</table>

<div>
    <h3>Оберіть excel-файл для заватаження</h3>
    @using (Html.BeginForm("Import", "Rubrics", FormMethod.Post, new { enctype = "multipart/form-data", id = "frm-excel" }))
    {
        <div>
            Завантажте Excel-файл:
            <input class="btn-primary" type="file" name="fileExcel" id="fileExcel" />
            <div>
                <input class="btn btn-primary" type="submit" value="Завантажити на сайт" />
            </div>
        </div>
    }
</div>


<div style="margin-top:20px;">
    <h3>Завантаження інформації щодо розподілу документів за рубриками в файл </h3>
    <a asp-action="Export" class="btn btn-primary" > Завантажити з сайту </a>
</div>